# Generated by Django 5.1.3 on 2024-11-21 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('valore_commessa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_inizio_lavori', models.DateField(blank=True, null=True)),
                ('data_fine_lavori', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cantiere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('p_iva_cf', models.CharField(blank=True, max_length=40, null=True)),
                ('pec', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('banca', models.CharField(blank=True, max_length=40, null=True)),
                ('iban', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'fornitori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Responsabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'responsabile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipologiaLavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipologia_lavori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('cognome', models.CharField(blank=True, max_length=60, null=True)),
                ('indirizzo', models.TextField(blank=True, null=True)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('numero_tel', models.CharField(blank=True, max_length=40, null=True)),
                ('banca', models.CharField(blank=True, max_length=60, null=True)),
                ('iban', models.CharField(blank=True, max_length=60, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_cliente', to='home.cantiere')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_ordine', to='home.cantiere')),
                ('fornitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_ordine', to='home.fornitori')),
            ],
            options={
                'db_table': 'ordine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazzino_ordine', to='home.ordine')),
            ],
            options={
                'db_table': 'magazzino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fatture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('n_fattura', models.CharField(blank=True, db_column='n.fattura', max_length=40, null=True)),
                ('data_fattura', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pagato', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_fatture', to='home.ordine')),
            ],
            options={
                'db_table': 'fatture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('quantita', models.IntegerField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_articoli', to='home.ordine')),
            ],
            options={
                'db_table': 'articoli',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('cognome', models.CharField(blank=True, max_length=40, null=True)),
                ('wage_lordo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('wage_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_personale', to='home.cantiere')),
                ('tipologia_lavoro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipolavoro_personale', to='home.tipologialavori')),
            ],
            options={
                'db_table': 'personale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantieri_azienda', to='home.cantiere')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_azienda', to='home.cliente')),
                ('personale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personale_azienda', to='home.personale')),
            ],
            options={
                'db_table': 'azienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assegnato_Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_assegnato', to='home.cantiere')),
                ('personale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personale_assegnato', to='home.personale')),
            ],
            options={
                'db_table': 'assegnato_cantiere',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fornitori',
            name='responsabile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsabile_fornitori', to='home.responsabile'),
        ),
        migrations.AddField(
            model_name='cantiere',
            name='responsabile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsabile_cantiere', to='home.responsabile'),
        ),
    ]
