# Generated by Django 5.1.3 on 2024-12-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'azienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondizioniPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpag_id', models.CharField(max_length=10, unique=True)),
                ('desc', models.CharField(blank=True, max_length=70, null=True)),
                ('tiporate', models.IntegerField(blank=True, null=True)),
                ('ggscdfix', models.IntegerField(blank=True, null=True)),
                ('tipopag', models.IntegerField(blank=True, null=True)),
                ('numrate', models.IntegerField(blank=True, null=True)),
                ('gg1rata', models.IntegerField(blank=True, null=True)),
                ('ggrate', models.IntegerField(blank=True, null=True)),
                ('tiposcad', models.CharField(blank=True, max_length=3, null=True)),
                ('ggfixant', models.CharField(blank=True, max_length=3, null=True)),
                ('ggdopofm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condizionipagamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipologiaLavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipologia_lavori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('prov', models.CharField(blank=True, max_length=40, null=True)),
                ('codfisc', models.CharField(blank=True, max_length=40, null=True)),
                ('partiva', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('codpag', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True)),
                ('pec', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('banca', models.CharField(blank=True, max_length=40, null=True)),
                ('iban', models.CharField(blank=True, max_length=40, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_cliente', to='home.azienda')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('valore_commessa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_inizio_lavori', models.DateField(blank=True, null=True)),
                ('data_fine_lavori', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cantiere', to='home.cliente')),
            ],
            options={
                'db_table': 'cantiere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clfr', models.CharField(blank=True, choices=[('C', 'Cliente'), ('F', 'Fornitore')], default='C', max_length=2, null=True)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('prov', models.CharField(blank=True, max_length=40, null=True)),
                ('codfisc', models.CharField(blank=True, max_length=40, null=True)),
                ('partiva', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True)),
                ('pec', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('banca', models.CharField(blank=True, max_length=40, null=True)),
                ('iban', models.CharField(blank=True, max_length=40, null=True)),
                ('codpag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pppp', to='home.condizionipagamento', to_field='codpag_id')),
            ],
            options={
                'db_table': 'fornitori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('magazzino', models.BooleanField(default=False)),
                ('tipologia', models.CharField(blank=True, choices=[('SE', 'Servizio'), ('MT', 'Materiale'), ('MC', 'Macchinari')], default='MT', max_length=2, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_ordine', to='home.cantiere')),
                ('fornitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_ordine', to='home.fornitori')),
            ],
            options={
                'db_table': 'ordine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.IntegerField(blank=True, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_magazzino', to='home.ordine')),
            ],
            options={
                'db_table': 'magazzino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fatture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('n_fattura', models.CharField(blank=True, db_column='n.fattura', max_length=40, null=True)),
                ('data_fattura', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pagato', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_fatture', to='home.ordine')),
            ],
            options={
                'db_table': 'fatture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('quantita', models.IntegerField(blank=True, null=True)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_articoli', to='home.ordine')),
            ],
            options={
                'db_table': 'articoli',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('cognome', models.CharField(blank=True, max_length=40, null=True)),
                ('responsabile', models.BooleanField(default=False)),
                ('wage_lordo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('wage_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_personale', to='home.azienda')),
                ('tipologia_lavoro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipolavoro_personale', to='home.tipologialavori')),
            ],
            options={
                'db_table': 'personale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assegnato_Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabile', models.BooleanField(default=False)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_assegnato', to='home.cantiere')),
                ('personale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personale_assegnato', to='home.personale')),
            ],
            options={
                'db_table': 'assegnato_cantiere',
                'managed': True,
                'unique_together': {('personale', 'cantiere')},
            },
        ),
    ]
