# Generated by Django 5.0.2 on 2024-02-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavorieffettuatifornitori',
            old_name='cantiere_id',
            new_name='cantiere',
        ),
        migrations.RenameField(
            model_name='lavorieffuttuatipersonale',
            old_name='cantiere_id',
            new_name='cantiere',
        ),
        migrations.RenameField(
            model_name='lavorieffuttuatipersonale',
            old_name='personale_id',
            new_name='personale',
        ),
        migrations.RenameField(
            model_name='tipologiapersonale',
            old_name='personale_id',
            new_name='personale',
        ),
    ]
