# Generated by Django 5.0.2 on 2024-02-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cantiere_id_lavorieffettuatifornitori_cantiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavorieffettuatifornitori',
            name='fornitore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitore', to='home.anagraficafornitori'),
        ),
        migrations.AlterField(
            model_name='lavorieffettuatifornitori',
            name='tipologia_lavori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lavori_fornitore_tipologia', to='home.tipologialavori'),
        ),
    ]
