# Generated by Django 5.1.3 on 2024-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_codpag_id_condizionipagamento_codpag'),
    ]

    operations = [
        migrations.AddField(
            model_name='condizionipagamento',
            name='rataiva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
