# Generated by Django 5.1.3 on 2024-11-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_azienda_fatture_remove_azienda_fornitore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personale',
            name='cantiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_peronale', to='home.cantiere'),
        ),
    ]
