# Generated by Django 5.0.3 on 2024-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lavorieffettuatifornitori_fornitore_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LavoriEffuttuatiPersonale',
            new_name='LavoriEffettuatiPersonale',
        ),
        migrations.RemoveField(
            model_name='cantiere',
            name='valore_commessa_currency',
        ),
        migrations.AlterField(
            model_name='cantiere',
            name='valore_commessa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
