# Generated by Django 5.1.3 on 2024-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_condizionipagamento_rataiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condizionipagamento',
            name='tiporate',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
