# Generated by Django 5.1.3 on 2024-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_condizionipagamento_tiporate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornitori',
            old_name='pec',
            new_name='cogn_pf',
        ),
        migrations.AddField(
            model_name='fornitori',
            name='fax',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='fmemo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='nome_pf',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='pec_fe',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='persoc',
            field=models.CharField(blank=True, choices=[('P', 'Persona'), ('S', 'Societa')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='resprap',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fornitori',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('SE', 'Servizio'), ('MA', 'Materiale'), ('NO', 'Noleggio')], default='MA', max_length=2, null=True),
        ),
    ]
