# Generated by Django 5.1.3 on 2024-11-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_personale_wage_lordo_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantiere',
            name='valore_commessa_currency',
        ),
        migrations.RemoveField(
            model_name='fatture',
            name='importo_currency',
        ),
        migrations.RemoveField(
            model_name='fatture',
            name='pagato_currency',
        ),
        migrations.AlterField(
            model_name='cantiere',
            name='valore_commessa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='fatture',
            name='pagato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
