# Generated by Django 5.1.3 on 2024-12-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_pec_fornitori_cogn_pf_fornitori_fax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='codcf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='pec',
            new_name='cogn_pf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='descrizione',
            new_name='fmemo',
        ),
        migrations.RenameField(
            model_name='fornitori',
            old_name='nome',
            new_name='codcf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codpag',
        ),
        migrations.RemoveField(
            model_name='fornitori',
            name='clfr',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fax',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_pf',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pec_fe',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persoc',
            field=models.CharField(blank=True, choices=[('P', 'Persona'), ('S', 'Societa')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=2, null=True),
        ),
    ]
