# Generated by Django 5.1.3 on 2024-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cantiere_valore_commessa_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articoli',
            name='importo_currency',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='importo_currency',
        ),
        migrations.AlterField(
            model_name='articoli',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
