# Generated by Django 5.1.3 on 2024-12-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_nome_cliente_codcf_rename_pec_cliente_cogn_pf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazzino',
            old_name='dummy',
            new_name='quantita',
        ),
        migrations.RemoveField(
            model_name='magazzino',
            name='ordine',
        ),
        migrations.AddField(
            model_name='magazzino',
            name='articolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magazzino_articoli', to='home.articoli'),
        ),
    ]
