# Generated by Django 5.1.3 on 2024-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_importo_articoli_importo_totale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='magazzino',
            field=models.BooleanField(default=False),
        ),
    ]
