# Generated by Django 5.1.3 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ordine_magazzino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='azienda',
        ),
        migrations.RemoveField(
            model_name='personale',
            name='azienda',
        ),
        migrations.AddField(
            model_name='personale',
            name='ore_lavorate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
