# Generated by Django 5.1.3 on 2024-12-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_cliente_banca_remove_cliente_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazzino',
            name='ordine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_magazzino', to='home.ordine'),
        ),
    ]
