# Generated by Django 5.1.3 on 2024-12-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_magazzino_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_cliente', to='home.azienda'),
        ),
        migrations.AddField(
            model_name='personale',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_personale', to='home.azienda'),
        ),
    ]
