# Generated by Django 5.1.3 on 2024-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cliente_azienda_personale_azienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
