# Generated by Django 5.1.3 on 2024-12-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_azienda_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='azienda',
        ),
        migrations.CreateModel(
            name='AziendeClienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda', to='home.azienda')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='home.cliente')),
            ],
        ),
    ]
