# Generated by Django 5.1.3 on 2024-12-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_cliente_azienda_aziendeclienti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aziendeclienti',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='aziendeclienti',
            table='aziendeclienti',
        ),
    ]
