# Generated by Django 5.1.4 on 2024-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_usersazienda_azienda_alter_usersazienda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personale',
            name='ore_lavorate',
        ),
        migrations.AddField(
            model_name='assegnato_cantiere',
            name='ore_lavorate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
