# Generated by Django 5.1.4 on 2024-12-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_personale_ore_lavorate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantiere',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='azienda',
        ),
        migrations.AddField(
            model_name='cantiere',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_cantiere', to='home.azienda'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_cliente', to='home.cantiere'),
        ),
    ]
