# Generated by Django 5.1.4 on 2024-12-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_cantiere_cliente_remove_cliente_azienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantiere',
            name='azienda',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cantiere',
        ),
        migrations.AddField(
            model_name='cantiere',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cantiere', to='home.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_cliente', to='home.azienda'),
        ),
    ]
