# Generated by Django 5.1.4 on 2024-12-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_cantiere_azienda_remove_cliente_cantiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitori',
            name='azienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_fornitore', to='home.azienda'),
        ),
    ]
