# Generated by Django 5.1.4 on 2024-12-23 16:50

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_personale_prova'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=80, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=home.models.Documenti.set_path)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_documenti', to='home.cantiere')),
            ],
        ),
    ]
