# Generated by Django 5.1.4 on 2024-12-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_documenti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenti',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='documenti',
            table='documenti',
        ),
    ]
